import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "./schema.js";
import bcrypt from "bcryptjs";

// Check if DATABASE_URL is valid Neon connection
const databaseUrl = process.env.DATABASE_URL;

export let db: any = null;
export let isNeonConnected = false;

if (databaseUrl && databaseUrl.includes("postgres") && !databaseUrl.includes("sample")) {
  try {
    const sql = neon(databaseUrl);
    db = drizzle(sql, { schema });
    isNeonConnected = true;
    console.log("Connected to Neon PostgreSQL database");
  } catch (err) {
    console.warn("Could not connect to Neon PostgreSQL, falling back to storage provider:", err);
  }
}

// In-Memory resilient repository for fast local preview & fallback
export interface MemoryStore {
  adminUsers: Array<any>;
  products: Array<any>;
  orders: Array<any>;
  orderItems: Array<any>;
  vendors: Array<any>;
  purchaseHistory: Array<any>;
  transactions: Array<any>;
  activityLogs: Array<any>;
  storeSettings: any;
}

const defaultAdminPasswordHash = bcrypt.hashSync("admin123", 10);

export const memoryDb: MemoryStore = {
  adminUsers: [
    {
      id: 1,
      username: "admin",
      password_hash: defaultAdminPasswordHash,
      nama: "Jeres Owner",
      role: "owner",
      created_at: new Date().toISOString(),
    },
    {
      id: 2,
      username: "staff",
      password_hash: defaultAdminPasswordHash,
      nama: "Rian Kasir",
      role: "staff",
      created_at: new Date().toISOString(),
    }
  ],
  products: [
    {
      id: 1,
      kategori: "stiker",
      nama_item: "Stiker Vinyl Glossy / Matte (Meteran)",
      deskripsi: "Cetak stiker bahan vinyl waterproof, tahan cuaca outdoor, sudah termasuk cutting kiss cut / die cut.",
      satuan: "meter",
      harga: 85000,
      harga_minimum_qty: 1,
      gambar_url: "https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 2,
      kategori: "stiker",
      nama_item: "Stiker Hologram Custom / Die Cut",
      deskripsi: "Stiker efek kilau pelangi hologram premium, daya rekat kuat untuk helm, tumbler, laptop.",
      satuan: "lembar",
      harga: 18000,
      harga_minimum_qty: 5,
      gambar_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 3,
      kategori: "dtf",
      nama_item: "Cetak DTF Sablon Kaos (Meteran 58cm)",
      deskripsi: "Direct to Film transfer film siap press ke kaos, hoodie, totebag. Warna pekat, lentur, tahan cuci.",
      satuan: "meter",
      harga: 65000,
      harga_minimum_qty: 1,
      gambar_url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 4,
      kategori: "dtf",
      nama_item: "DTF Ukuran A3 Siap Press (Kaos Custom)",
      deskripsi: "Paket DTF ukuran cetak 28x40cm, warna full color CMYK + White, hasil halus tajam.",
      satuan: "lembar",
      harga: 25000,
      harga_minimum_qty: 2,
      gambar_url: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 5,
      kategori: "banner",
      nama_item: "Banner Flexi 280gr Outdoor (Spanduk)",
      deskripsi: "Spanduk promosi standar outdoor warna cerah, sudah termasuk mata ayam tiap sudut.",
      satuan: "meter",
      harga: 25000,
      harga_minimum_qty: 1,
      gambar_url: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 6,
      kategori: "banner",
      nama_item: "X-Banner / Y-Banner Lengkap Rangka (60x160cm)",
      deskripsi: "Cetak bahan Albatros / Flexi tebal anti keriting dengan standing tripod kokoh siap display.",
      satuan: "pcs",
      harga: 85000,
      harga_minimum_qty: 1,
      gambar_url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 7,
      kategori: "jersey",
      nama_item: "Jersey Full Printing Sublim (Milano/Dryfit)",
      deskripsi: "Jersey futsal/sepeda/esport full sublim warna bebas, bahan adem menyerap keringat, custom nama & nomor.",
      satuan: "pcs",
      harga: 120000,
      harga_minimum_qty: 6,
      gambar_url: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 8,
      kategori: "desain",
      nama_item: "Jasa Desain Grafis / Setting Cetak",
      deskripsi: "Pembuatan konsep desain logo, banner, kemasan, atau layout cetak hingga ACC siap produksi.",
      satuan: "paket",
      harga: 50000,
      harga_minimum_qty: 1,
      gambar_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 9,
      kategori: "lainnya",
      nama_item: "Nota 2 Ply / Carbonless Custom (Ukuran 1/4 Folio)",
      deskripsi: "Buku nota NCR 2 rangkap 50 set per buku, nomorator + perforasi rapi.",
      satuan: "lusin",
      harga: 145000,
      harga_minimum_qty: 1,
      gambar_url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&auto=format&fit=crop&q=80",
      ],
      is_active: true,
      tampilkan_harga_publik: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  ],
  orders: [
    {
      id: 1,
      nomor_nota: "INV-20250820-0001",
      nama_pelanggan: "Budi Pratama (Kedai Kopi Santai)",
      no_wa: "081298765432",
      tanggal_order: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      tanggal_ambil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: "proses",
      metode_bayar: "Transfer BCA",
      status_bayar: "dp",
      jumlah_dp: 150000,
      catatan: "Desain logo cup sudah ACC via WA, mohon cutting kiss cut bulat diameter 5cm.",
      subtotal: 255000,
      diskon: 15000,
      total: 240000,
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 2,
      nomor_nota: "INV-20250821-0002",
      nama_pelanggan: "Komunitas Futsal Garuda",
      no_wa: "085712345678",
      tanggal_order: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      tanggal_ambil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      status: "pending",
      metode_bayar: "Cash",
      status_bayar: "belum",
      jumlah_dp: 0,
      catatan: "Jersey 12 pcs size L (8) dan XL (4), list nama pemain terlampir di WA.",
      subtotal: 1440000,
      diskon: 40000,
      total: 1400000,
      created_by: "Rian Kasir",
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 3,
      nomor_nota: "INV-20250819-0003",
      nama_pelanggan: "Siti Rahma (Toko Berkah Snack)",
      no_wa: "087811223344",
      tanggal_order: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      tanggal_ambil: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: "selesai",
      metode_bayar: "QRIS",
      status_bayar: "lunas",
      jumlah_dp: 160000,
      catatan: "Banner warung 3x1 meter + stiker label 2 meter. Sudah diambil pelanggan.",
      subtotal: 170000,
      diskon: 10000,
      total: 160000,
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    }
  ],
  orderItems: [
    {
      id: 1,
      order_id: 1,
      product_id: 1,
      nama_item: "Stiker Vinyl Glossy / Matte (Meteran)",
      qty: 3,
      satuan: "meter",
      harga_satuan: 85000,
      subtotal: 255000,
      catatan_item: "Cutting bulat 5cm, laminasi glossy anti gores",
    },
    {
      id: 2,
      order_id: 2,
      product_id: 7,
      nama_item: "Jersey Full Printing Sublim (Milano/Dryfit)",
      qty: 12,
      satuan: "pcs",
      harga_satuan: 120000,
      subtotal: 1440000,
      catatan_item: "Bahan dryfit milano, nomor punggung emas",
    },
    {
      id: 3,
      order_id: 3,
      product_id: 5,
      nama_item: "Banner Flexi 280gr Outdoor (Spanduk)",
      qty: 3,
      satuan: "meter",
      harga_satuan: 25000,
      subtotal: 75000,
      catatan_item: "Ukuran 3x1m mata ayam 4 sudut",
    },
    {
      id: 4,
      order_id: 3,
      product_id: 1,
      nama_item: "Stiker Vinyl Glossy / Matte (Meteran)",
      qty: 1,
      satuan: "meter",
      harga_satuan: 85000,
      subtotal: 85000,
      catatan_item: "Label kemasan keripik",
    },
    {
      id: 5,
      order_id: 3,
      product_id: 8,
      nama_item: "Jasa Desain Grafis / Setting Cetak",
      qty: 1,
      satuan: "paket",
      harga_satuan: 10000,
      subtotal: 10000,
      catatan_item: "Setting ulang font banner",
    }
  ],
  vendors: [
    {
      id: 1,
      nama_vendor: "CV Mitra Sticker Mandiri",
      kategori_supply: "Bahan Stiker",
      kontak_nama: "Pak Hendra",
      no_wa: "081122334455",
      alamat: "Kawasan Industri Pergudangan Blok C4, Surabaya",
      catatan: "Supplier bahan Ritrama, Maxdecal, Camel. Tempo 14 hari.",
      is_active: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 2,
      nama_vendor: "Indo DTF Film & Ink Supply",
      kategori_supply: "Bahan DTF",
      kontak_nama: "Ko William",
      no_wa: "081299887766",
      alamat: "Ruko Daan Mogot Permai No. 12, Jakarta Barat",
      catatan: "PET Film Premium Single Matte & Tinta CMYK DuPont.",
      is_active: true,
      created_at: new Date().toISOString(),
    },
    {
      id: 3,
      nama_vendor: "Pabrik Spanduk & Flexi Cemerlang",
      kategori_supply: "Bahan Banner",
      kontak_nama: "Ibu Diana",
      no_wa: "085677889900",
      alamat: "Jl. Industri Raya No. 88, Sidoarjo",
      catatan: "Roll Flexi 280gr, 340gr, Korcin, X-Banner Stand.",
      is_active: true,
      created_at: new Date().toISOString(),
    }
  ],
  purchaseHistory: [
    {
      id: 1,
      vendor_id: 1,
      tanggal: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      nama_barang: "Vinyl Glossy Maxdecal 1.05m x 50m (1 Roll)",
      qty: 1,
      satuan: "roll",
      harga_satuan: 950000,
      total: 950000,
      catatan: "Bahan stok mingguan stiker label",
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 2,
      vendor_id: 2,
      tanggal: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      nama_barang: "PET Film DTF 60cm x 100m + Hotmelt Powder 5kg",
      qty: 1,
      satuan: "paket",
      harga_satuan: 1450000,
      total: 1450000,
      catatan: "Untuk kebutuhan cetak DTF sablon kaos",
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    }
  ],
  transactions: [
    {
      id: 1,
      tipe: "masuk",
      kategori: "Penjualan Order Cetak",
      nominal: 255000,
      tanggal: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "Transfer BCA",
      keterangan: "Pelunasan Cetak Stiker Vinyl 3m (Bpk. Agus Prasetyo)",
      referensi: "INV-20250821-0001",
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 2,
      tipe: "keluar",
      kategori: "Kulakan Bahan Baku",
      nominal: 950000,
      tanggal: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "Transfer BCA",
      keterangan: "Pembelian Vinyl Glossy Maxdecal 1 Roll (CV Mitra Sticker Mandiri)",
      referensi: "Kulakan #1",
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 3,
      tipe: "masuk",
      kategori: "Penjualan Order Cetak",
      nominal: 160000,
      tanggal: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "QRIS",
      keterangan: "Pelunasan Banner Spanduk & Stiker (Ibu Siti Rahma)",
      referensi: "INV-20250819-0003",
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 4,
      tipe: "keluar",
      kategori: "Kulakan Bahan Baku",
      nominal: 1450000,
      tanggal: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "Transfer Mandiri",
      keterangan: "Pembelian PET Film DTF + Powder Hotmelt (Indo DTF Supply)",
      referensi: "Kulakan #2",
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 5,
      tipe: "masuk",
      kategori: "Jasa Desain & Setting",
      nominal: 150000,
      tanggal: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "Cash",
      keterangan: "Jasa Pembuatan Desain Logo & Vektor Maskot Toko Roti",
      referensi: "-",
      created_by: "Rian Kasir",
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 6,
      tipe: "keluar",
      kategori: "Listrik, Air & Internet",
      nominal: 385000,
      tanggal: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "Transfer BCA",
      keterangan: "Tagihan Listrik PLN Workshop Percetakan & Token Cadangan",
      referensi: "PLN-882193",
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 7,
      tipe: "keluar",
      kategori: "Perawatan & Sparepart Mesin",
      nominal: 120000,
      tanggal: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      metode_pembayaran: "Cash",
      keterangan: "Cairan Cleaner Head DTF, Wiper Blade, & Sarung Tangan Nitril",
      referensi: "-",
      created_by: "Jeres Owner",
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 8,
      tipe: "masuk",
      kategori: "Penjualan Order Cetak",
      nominal: 700000,
      tanggal: new Date().toISOString(),
      metode_pembayaran: "Transfer BCA",
      keterangan: "DP 50% Pembuatan Jersey Tim Futsal (Komunitas Futsal Garuda)",
      referensi: "INV-20250821-0002",
      created_by: "Rian Kasir",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  ],
  activityLogs: [
    {
      id: 1,
      user_name: "Jeres Owner",
      action: "Login Admin",
      details: "Owner berhasil masuk ke dashboard sistem",
      created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 2,
      user_name: "Rian Kasir",
      action: "Buat Order Baru",
      details: "Membuat nota order INV-20250821-0002 untuk Komunitas Futsal Garuda",
      created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    }
  ],
  storeSettings: {
    id: 1,
    nama_toko: "Jeres Studio",
    slogan: "Percetakan Digital, Stiker, DTF & Sablon Jersey Berkualitas",
    alamat: "Jl. Percetakan Raya No. 134, Pusat Usaha Kreatif",
    no_wa: "6281234567890",
    email: "jeresstudio134@gmail.com",
    logo_url: "",
    rekening_bank: "BCA: 123-456-7890 (a/n Jeres Studio)\nMandiri: 987-654-3210 (a/n Jeres Studio)\nQRIS: Semua E-Wallet & M-Banking",
    catatan_nota: "1. Barang yang sudah dicetak sesuai ACC proofing tidak dapat dibatalkan/diretur.\n2. Pelunasan wajib dilakukan saat serah terima barang.\n3. File master dan backup disimpan sistem selama 30 hari kalender.",
    updated_at: new Date().toISOString(),
  }
};
